name: depi227
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.6.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  firebase_analytics: ^12.0.4
  firebase_messaging: ^16.0.4
  google_sign_in: ^7.2.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  uuid: ^4.5.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/medilink_logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
